### ISSUE TITLE
round corners of some "boxes"

### ISSUE THREAD

**Issue by Lashaka** [Lashaka/Fun-Camera#12]
@ChariBasaur

**Comment by lashaka** [comment]
Hard with winform, consider converting Figma components to picture & use

**Comment by Lashaka** [comment]
@ChariBasaur  in winform, it is an issue to round up buttons without a library, now i've worked a lot on this thing. well.. i think its better without.
![BEST ROUNDED BUTTON](https://user-images.githubusercontent.com/69360460/211843404-3dc3741a-0c04-45a6-b72d-3fe3a1d56c03.png)

**Comment by Lashaka** [comment]
@ChariBasaur 
picked a different design mosre suitable for winforms
![Untitled](https://user-images.githubusercontent.com/69360460/211850538-4444539e-77cf-48a4-8d25-12a3e0b028cd.png)
