### ISSUE TITLE
update Read me

### ISSUE THREAD

**Issue by elior7557** [Lashaka/Fun-Camera#4]
add section in readme "How To Run"
**Description:** As someone who hasn't used C# in a while, I don't remember how to run .sln files. It would be helpful to have a "How To Run" section in the Readme that describes the process for running the project. This would be especially useful for new contributors or users who are not familiar with the project's setup.

**Comment by lashaka** [comment]
@elior7557  i will darling, thanks for the note! will probably happen after the UI will be added.  :face_with_spiral_eyes:

**Comment by Lashaka** [comment]
@elior7557  you can now run it using the Run here folder
