### ISSUE TITLE
QA for first UI version

### ISSUE THREAD

**Issue by lashaka** [lashaka/Fun-Camera#7]
check new Version, tell me what should be changed added redesigned etc @ChariBasaur

**Comment by ChariBasaur** [comment]
my friend
there are allot of elements that I designed in the figma file that I've shared with you that are missing in the end product.
I would like you to open the, look at the following categories and make the appropriate changes:
> fonts (i used semi bold/regular roboto)
> rounded corners of some "boxes", frames if you will
> the size of elements, for example the off white rectangle behind the camera screens
> drop shadows and inner shadows

P.S. the "flip X" and "flip Y" effects each do the other one's job, change their names

thank you in advance

**Comment by lashaka** [comment]
@ChariBasaur  thanks, note that next time, open issues with all the notes you gave to me and then click on "Close With Comment" , because you've completed this mission, doing QA.
