### ISSUE TITLE
Need a logo for the application 

### ISSUE THREAD

**Issue by lashaka** [lashaka/Fun-Camera#8]
right now we have a default logo, make something simple to appear on the corner of the window, thanks.

**Comment by ChariBasaur** [comment]
sure i'm on it

**Comment by ChariBasaur** [comment]
<img width="80" alt="fun camera icon 1" src="https://user-images.githubusercontent.com/121454275/211781667-1e4c58cf-18a0-474e-a57d-ec6d255f12f4.png">

here

**Comment by ChariBasaur** [comment]
you like?

**Comment by ChariBasaur** [comment]
if you like close the issue

**Comment by lashaka** [comment]
great i used it.
